### ISSUE TITLE
[Q] Support for Coveralls.io and Appveyor?

### ISSUE THREAD

**Issue by thatsIch** [randy3k/UnitTesting-example#4]
Currently there is only integration between coveralls and travis. But for me I only program in a windows specific domain, thus I am more interested building them in a windows environment via AppVeyor. But I saw, that there is no coveralls integration. Any plans adding that?

**Comment by randy3k** [comment]
Unfortunately, I don't have enough time to figure out how to use Coveralls.io on AppVeyor. It will be helpful if you can point me to some references on how to download coveralls binary and submit the result to coveralls.io on AppVeyor platform.

**Comment by thatsIch** [comment]
I tried to run it with

https://github.com/z4r/python-coveralls and
https://github.com/coagulant/coveralls-python

but I can not hook the coverage option into your `ps1`. 

I just use pip to install coveralls like with https://pypi.python.org/pypi/coveralls

**Comment by randy3k** [comment]
With the [dev][1] branch of UnitTesting, I am able to generate the [coverage report][2]. But I found no way to update the `.coverage` file to coveralls.io.


[1]: https://github.com/randy3k/UnitTesting/tree/dev
[2]: https://ci.appveyor.com/project/randy3k/unittesting/build/1.0.515/job/vy4dddpwxftqvil9

**Comment by thatsIch** [comment]
I have got it running by

1. installing coveralls with `pip install coveralls` or similar
2. copying the `.coverage` file to the git repository
3. (run `cover report` to check if an actual report can be generated from the `.coverage` file)
4. set the envionment variable required for coveralls.io `SET COVERALLS_REPO_TOKEN=XXXXXXXX`
5. run `coveralls`

I am not sure if every plugin has to copy the `.coverage` file to the git repository, but then I searched a bit and it seems if you use the other coveralls from https://pypi.python.org/pypi/python-coveralls you can specify the data path but it expects JSON and thus uses another python module to generate the data.

**Comment by thatsIch** [comment]
Note that both are have clashing pathes since both are called `coveralls.exe`. You can "easily" switch by using `pip install coveralls --upgrade --force-reinstall`

**Comment by randy3k** [comment]
I finally got it working. But coveralls.io doesn't support grouping appveyor sub-builds, or merging appveyor reports and travis-ci reports. It makes the feature less useful. Check https://github.com/randy3k/UnitTesting/blob/2b3d0496bd1f3dc9556bcc19057bc5fbfa345764/appveyor.yml#L28

**Comment by randy3k** [comment]
For instance, [one sub build][1] is numbered as Job # 625.1 while [another sub build][2] is numbered as Job #626.1.

[1]: https://ci.appveyor.com/project/randy3k/unittesting/build/1.0.582/job/o96ew142f72k1g8m
[2]: https://ci.appveyor.com/project/randy3k/unittesting/build/1.0.582/job/9c5sq6visvf8wqg9

**Comment by randy3k** [comment]
New version of UnitTesting has released, check [appveyor.yml](https://github.com/randy3k/UnitTesting-example/blob/c77b0b5f391304573fc7b7b07dc0a6776f6135ea/appveyor.yml#L26) for the instructions.

**Comment by thatsIch** [comment]
Technically it supports it like https://coveralls.io/builds/560853

It seems you can use something like `coverage combine X Y Z`. Not if appveyor uses the same machine instance.

[1] http://coverage.readthedocs.io/en/coverage-4.2/cmd.html
[2] http://stackoverflow.com/questions/26214055/combine-python-coverage-files

**Comment by thatsIch** [comment]
Thanks, I got it running. Thanks for the integration with the `-coverage` hook.

**Comment by randy3k** [comment]
The `.coverage` is copied automatically so that [this](https://github.com/thatsIch/sublime-rainmeter/blob/340c2625be7a38bbe22c3cad3e9a97fa5d191bcc/appveyor.yml#L25) is not needed.

**Comment by thatsIch** [comment]
ah nice, thanks for the headsup
