### ISSUE TITLE
`sys.modules` vs `import`

### ISSUE THREAD

**Issue by mreq** [randy3k/UnitTesting-example#6]
Why is `sys.modules` used in the example? Am by no means fluent in python, but had trouble getting the `sys.modules` way to work. Isn't `import` the standard?

```python
sys.modules['SublimeMagic.context']
# vs
from SublimeMagic.context import context
```

**Comment by randy3k** [comment]
Some package names are space separated, in those cases, `sys.modules` will be needed.

**Comment by mreq** [comment]
Oh I see. Allright, thanks.
